# Generated by Django 4.1.11 on 2023-10-23 08:12

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=300)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=10)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("User", "User"),
                            ("Retailer", "Retailer"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_golden", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "category_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("category_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "product_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                (
                    "category_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amazon.categories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specifications",
            fields=[
                (
                    "spec_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("color", models.CharField(max_length=20)),
                ("dimensions", models.CharField(max_length=20)),
                ("size", models.CharField(max_length=20)),
                ("material", models.CharField(max_length=20)),
                ("weight", models.CharField(max_length=20)),
                ("manufacturer", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Wishlists",
            fields=[
                (
                    "wishlist_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                ("time_added", models.TimeField(auto_now_add=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amazon.products",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="products",
            name="spec_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="amazon.specifications",
            ),
        ),
        migrations.CreateModel(
            name="Carts",
            fields=[
                (
                    "cart_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("quantity", models.IntegerField()),
                ("date_added", models.DateField(auto_now_add=True)),
                ("time_added", models.TimeField(auto_now_add=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amazon.products",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cards",
            fields=[
                (
                    "card_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("card_number", models.CharField(max_length=20)),
                ("pin", models.IntegerField()),
                (
                    "card_type",
                    models.CharField(
                        choices=[("Debit", "Debit"), ("Credit", "Credit")], max_length=6
                    ),
                ),
                ("expiry_date", models.CharField(max_length=6)),
                ("name", models.CharField(max_length=50)),
                (
                    "user_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Addresses",
            fields=[
                (
                    "address_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("state", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=20)),
                ("pincode", models.CharField(max_length=6)),
                ("landmark", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
