# Generated by Django 4.1.11 on 2023-10-25 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "review_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("rating", models.IntegerField()),
                ("feedback", models.TextField()),
                ("date_added", models.DateField(auto_now_add=True)),
                ("time_added", models.TimeField(auto_now_add=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amazon.products",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewImages",
            fields=[
                (
                    "review_image_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("image_name", models.CharField(default=None, max_length=50)),
                (
                    "review_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amazon.reviews",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "product_image_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("image_name", models.CharField(default=None, max_length=50)),
                (
                    "product_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amazon.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("total", models.FloatField()),
                ("discounts", models.IntegerField()),
                ("grand_total", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Delivered", "Delivered"),
                            ("Returned", "Returned"),
                            ("Cancelled", "Cancelled"),
                            ("Failed", "Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                ("time_added", models.TimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                (
                    "order_details_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                (
                    "order_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amazon.orders",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amazon.products",
                    ),
                ),
            ],
        ),
    ]
